# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b70103ce004befa349ac8a36b8cfa5689ed3164bfbde4d0ef5967f9a98f56dd29a5c932082701789d1594a6c57cdbb0cf224598b8f3cf5142a453db9aabc599e

test:
  secret_key_base: 2c0119d56e95d4f7604548fdf7721935c24b396573c2cd6c47e7c01f5083e7acd717d1f6836c207ed66d6b51749a1cadd3ae0f011de4c83d33766bee2a437c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
